title: Oxford Gaming Study Information
description: Information for participants in our Oxford Internet Study on Gaming
theme: just-the-docs

url: https://digital-wellbeing.github.io/oxford-gaming-study

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
